import { z } from "zod";
import { TraceSchema } from "./synthesis.js";
import { AxisScoresSchema } from "./cluster.js";

/**
 * One synthetic input generated by Nia Document Agent (seed) and expanded
 * via the four programmatic variation knobs (D12).
 */
export const SyntheticInputSchema = z.object({
  input_id: z.string(),
  call_site_id: z.string(),
  /** "seed_<n>" or "seed_<n>:variant_<sub-id>" */
  origin: z.string(),
  payload: z.unknown(),
});
export type SyntheticInput = z.infer<typeof SyntheticInputSchema>;

/**
 * Each cell in the visible grid. Streamed back via Convex subscription to
 * the UI. Tier classification is set live as outputs land.
 */
export const SyntheticCellSchema = z.object({
  input_id: z.string(),
  worker_id: z.number().int().nonnegative(),
  status: z.enum(["queued", "in_flight", "done", "error"]),
  path: z.enum(["candidate", "oracle"]),
  tier_assigned: z.enum(["tier_1", "tier_2", "tier_3"]).optional(),
  output: z.unknown().optional(),
  cluster_id: z.string().optional(),
  latency_ms: z.number().nonnegative().optional(),
  cost_usd: z.number().nonnegative().optional(),
});
export type SyntheticCell = z.infer<typeof SyntheticCellSchema>;

/**
 * Online k-means cluster as it materializes during a Stage-2 run.
 */
export const OnlineClusterSchema = z.object({
  cluster_id: z.string(),
  centroid: z.array(z.number()),
  member_count: z.number().int().nonnegative(),
  /** Approximate fraction of the run captured by this cluster. */
  share: z.number().min(0).max(1),
  modal_output_shape: z.string(),
});
export type OnlineCluster = z.infer<typeof OnlineClusterSchema>;

/**
 * Live tier-mix stats; what the grid color-coding is summarizing.
 */
export const TierMixSchema = z.object({
  tier_1: z.number().int().nonnegative(),
  tier_2: z.number().int().nonnegative(),
  tier_3: z.number().int().nonnegative(),
});
export type TierMix = z.infer<typeof TierMixSchema>;

/**
 * Final output of one Stage-2 synthetic-confirmation run for a single call site.
 * Persisted to InsForge for audit (run_id deterministic from seed).
 */
export const SyntheticRunSchema = z.object({
  run_id: z.string(),
  call_site_id: z.string(),
  total_calls: z.number().int().positive(),
  oracle_calls: z.number().int().nonnegative(),
  candidate_calls: z.number().int().nonnegative(),
  worker_count: z.number().int().positive(),
  wall_time_ms: z.number().nonnegative(),
  throughput_per_sec: z.number().nonnegative(),
  axis_scores: AxisScoresSchema.extend({
    oracle_agreement: z.number().min(0).max(1),
  }),
  tier_mix: TierMixSchema,
  clusters: z.array(OnlineClusterSchema),
  /** Sample of (input, output) pairs preserved for the synthesis spec. */
  preserved_traces: z.array(TraceSchema),
  passes_synthesis_gate: z.boolean(),
});
export type SyntheticRun = z.infer<typeof SyntheticRunSchema>;

/** Stage-2 axis thresholds (D10). */
export const STAGE2_THRESHOLDS = {
  schema_stability: 0.95,
  determinism: 0.95,
  oracle_agreement: 0.92,
} as const;

/** Default scale parameters; tests and hackathon downscale freely. */
export const DEFAULT_SCALE = {
  total_calls: 100_000,
  oracle_fraction: 0.01,
  worker_count: 64,
  cluster_count_max: 50,
} as const;
